### PR TITLE
Fix `CthresholdUnproven` bugs in prover caused by multisig transaction

### LINKED ISSUE #597: Signing a multi-sig transaction in wasm caused an error
We create a multisig transaction with atleast(3, ...) script
then reduce transaction and store bytes to hex format.

```
inputBox1BytesHex = "80ade204100504000400040004000402d804d601b2a5730000d602e4c6a7041ad603e4c6a70510d604ad7202d901040ecdee7204ea02d19683020193c27201c2a7938cb2db63087201730100018cb2db6308a773020001eb02ea02d19683020193e4c67201041a720293e4c672010510720398b27203730300720498b272037304007204d18b0f01a6ac381e6fa99929fd1477b3ba9499790a775e91d4c14c5aa86e9a118dfac85301021a04210302e57ca7ebf8cfa1802d4bc79a455008307a936b4f50f0629d9bef484fdd5189210399f5724bbc4d08c6e146d61449c05a3e0546868b1d4f83411f325187d5ca4f8521024e06e6c6073e13a03fa4629882a69108cd60e0a9fbb2e0fcc898ce68a7051b6621027a069cc972fc7816539a316ba1cfc0164656d63dd1873ee407670b0e8195f3bd1002060865c7e0d4a77ccd605b3e4812d38140f7e68fdf740cb6cdc1d8957b75138d1e4c00"
inputBox1BytesHex = "80c8afa02510010e20a6ac381e6fa99929fd1477b3ba9499790a775e91d4c14c5aa86e9a118dfac853d1aea4d9010163aedb63087201d901034d0e938c7203017300d18b0f00002eca6f88ea99fb4fe313d94cb05c576b1b7a94ec7166aec958b36bcea4b8ff1a01"
txBytesHex = "ce04022f4cd0df4db787875b3a071e098b72ba4923bd2460e08184b34359563febe04700005e8269c8e2b975a43dc6e74a9c5b10b273313c6d32c1dd40c171fc0a8852ca0100000001a6ac381e6fa99929fd1477b3ba9499790a775e91d4c14c5aa86e9a118dfac8530480ade204100504000400040004000402d804d601b2a5730000d602e4c6a7041ad603e4c6a70510d604ad7202d901040ecdee7204ea02d19683020193c27201c2a7938cb2db63087201730100018cb2db6308a773020001eb02ea02d19683020193e4c67201041a720293e4c672010510720398b27203730300720498b272037304007204d18b0f010001021a04210302e57ca7ebf8cfa1802d4bc79a455008307a936b4f50f0629d9bef484fdd5189210399f5724bbc4d08c6e146d61449c05a3e0546868b1d4f83411f325187d5ca4f8521024e06e6c6073e13a03fa4629882a69108cd60e0a9fbb2e0fcc898ce68a7051b6621027a069cc972fc7816539a316ba1cfc0164656d63dd1873ee407670b0e8195f3bd100206088094ebdc030008cd0314368e16c9c99c5a6e20dda917aeb826b3a908becff543b3a36b38e6b3355ff5d18b0f0000c0843d1005040004000e36100204a00b08cd0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798ea02d192a39a8cc7a701730073011001020402d19683030193a38cc7b2a57300000193c2b2a57301007473027303830108cdeeac93b1a57304d18b0f0000c0af87c3210008cd0314368e16c9c99c5a6e20dda917aeb826b3a908becff543b3a36b38e6b3355ff5d18b0f00009702980304cd0302e57ca7ebf8cfa1802d4bc79a455008307a936b4f50f0629d9bef484fdd5189cd0399f5724bbc4d08c6e146d61449c05a3e0546868b1d4f83411f325187d5ca4f85cd024e06e6c6073e13a03fa4629882a69108cd60e0a9fbb2e0fcc898ce68a7051b66cd027a069cc972fc7816539a316ba1cfc0164656d63dd1873ee407670b0e8195f3bd9604cd0302e57ca7ebf8cfa1802d4bc79a455008307a936b4f50f0629d9bef484fdd5189cd0399f5724bbc4d08c6e146d61449c05a3e0546868b1d4f83411f325187d5ca4f85cd024e06e6c6073e13a03fa4629882a69108cd60e0a9fbb2e0fcc898ce68a7051b66cd027a069cc972fc7816539a316ba1cfc0164656d63dd1873ee407670b0e8195f3bdf39b03d3cb9e02d073"
```

signer secrets are :
```
00eda6c0e9fc808d4cf050fc4e98705372b9f0786a6b63aa4013d1a20539b104
00cc2e48e5e53059e0d68866eff97a6037cb39945ea9f09f40fcec82d12cd8cb8b
00c97250f41cfa8d545c2f8d75b2ee24002b5feec32340c2bb81fa4e2d4c7527d3
53ceef0ece83401cf5cd853fd0c1a9bbfab750d76f278b3187f1a14768d6e9c4
```

then write this code to load transaction and sign it using appkit:

```
    Configs.ergoClient.execute(ctx => {
      val txBytesHex = "ce04022f4cd0df4db787875b3a071e098b72ba4923bd2460e08184b34359563febe04700005e8269c8e2b975a43dc6e74a9c5b10b273313c6d32c1dd40c171fc0a8852ca0100000001a6ac381e6fa99929fd1477b3ba9499790a775e91d4c14c5aa86e9a118dfac8530480ade204100504000400040004000402d804d601b2a5730000d602e4c6a7041ad603e4c6a70510d604ad7202d901040ecdee7204ea02d19683020193c27201c2a7938cb2db63087201730100018cb2db6308a773020001eb02ea02d19683020193e4c67201041a720293e4c672010510720398b27203730300720498b272037304007204d18b0f010001021a04210302e57ca7ebf8cfa1802d4bc79a455008307a936b4f50f0629d9bef484fdd5189210399f5724bbc4d08c6e146d61449c05a3e0546868b1d4f83411f325187d5ca4f8521024e06e6c6073e13a03fa4629882a69108cd60e0a9fbb2e0fcc898ce68a7051b6621027a069cc972fc7816539a316ba1cfc0164656d63dd1873ee407670b0e8195f3bd100206088094ebdc030008cd0314368e16c9c99c5a6e20dda917aeb826b3a908becff543b3a36b38e6b3355ff5d18b0f0000c0843d1005040004000e36100204a00b08cd0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798ea02d192a39a8cc7a701730073011001020402d19683030193a38cc7b2a57300000193c2b2a57301007473027303830108cdeeac93b1a57304d18b0f0000c0af87c3210008cd0314368e16c9c99c5a6e20dda917aeb826b3a908becff543b3a36b38e6b3355ff5d18b0f00009702980304cd0302e57ca7ebf8cfa1802d4bc79a455008307a936b4f50f0629d9bef484fdd5189cd0399f5724bbc4d08c6e146d61449c05a3e0546868b1d4f83411f325187d5ca4f85cd024e06e6c6073e13a03fa4629882a69108cd60e0a9fbb2e0fcc898ce68a7051b66cd027a069cc972fc7816539a316ba1cfc0164656d63dd1873ee407670b0e8195f3bd9604cd0302e57ca7ebf8cfa1802d4bc79a455008307a936b4f50f0629d9bef484fdd5189cd0399f5724bbc4d08c6e146d61449c05a3e0546868b1d4f83411f325187d5ca4f85cd024e06e6c6073e13a03fa4629882a69108cd60e0a9fbb2e0fcc898ce68a7051b66cd027a069cc972fc7816539a316ba1cfc0164656d63dd1873ee407670b0e8195f3bdf39b03d3cb9e02d073"
      val reduced = ctx.parseReducedTransaction(Base16.decode(txBytesHex).get)
      val sks = Seq(
        BigInt(Base16.decode("00eda6c0e9fc808d4cf050fc4e98705372b9f0786a6b63aa4013d1a20539b104").get),
        BigInt(Base16.decode("00cc2e48e5e53059e0d68866eff97a6037cb39945ea9f09f40fcec82d12cd8cb8b").get),
        BigInt(Base16.decode("00c97250f41cfa8d545c2f8d75b2ee24002b5feec32340c2bb81fa4e2d4c7527d3").get),
        BigInt(Base16.decode("53ceef0ece83401cf5cd853fd0c1a9bbfab750d76f278b3187f1a14768d6e9c4").get)
      )
      sks.foreach(item => {
        println(Configs.addressEncoder.fromProposition(ctx.newProverBuilder().withDLogSecret(item.bigInteger).build().getAddress.getErgoAddress.script).get)
      })
      val proverBuilder = ctx.newProverBuilder()
      sks.foreach(item => proverBuilder.withDLogSecret(item.bigInteger))
      val prover = proverBuilder.build()
      prover.signReduced(reduced, 0)
    })
```

the transaction signed correctly without any problem.

But write same code in typescript using wasm

```
import * as wasm from 'ergo-lib-wasm-nodejs';

const secrets = [
    "00eda6c0e9fc808d4cf050fc4e98705372b9f0786a6b63aa4013d1a20539b104",
    "cc2e48e5e53059e0d68866eff97a6037cb39945ea9f09f40fcec82d12cd8cb8b",
    "c97250f41cfa8d545c2f8d75b2ee24002b5feec32340c2bb81fa4e2d4c7527d3",
    "53ceef0ece83401cf5cd853fd0c1a9bbfab750d76f278b3187f1a14768d6e9c4",
]
const reduced = wasm.ReducedTransaction.sigma_parse_bytes(Uint8Array.from(Buffer.from("ce04022f4cd0df4db787875b3a071e098b72ba4923bd2460e08184b34359563febe04700005e8269c8e2b975a43dc6e74a9c5b10b273313c6d32c1dd40c171fc0a8852ca0100000001a6ac381e6fa99929fd1477b3ba9499790a775e91d4c14c5aa86e9a118dfac8530480ade204100504000400040004000402d804d601b2a5730000d602e4c6a7041ad603e4c6a70510d604ad7202d901040ecdee7204ea02d19683020193c27201c2a7938cb2db63087201730100018cb2db6308a773020001eb02ea02d19683020193e4c67201041a720293e4c672010510720398b27203730300720498b272037304007204d18b0f010001021a04210302e57ca7ebf8cfa1802d4bc79a455008307a936b4f50f0629d9bef484fdd5189210399f5724bbc4d08c6e146d61449c05a3e0546868b1d4f83411f325187d5ca4f8521024e06e6c6073e13a03fa4629882a69108cd60e0a9fbb2e0fcc898ce68a7051b6621027a069cc972fc7816539a316ba1cfc0164656d63dd1873ee407670b0e8195f3bd100206088094ebdc030008cd0314368e16c9c99c5a6e20dda917aeb826b3a908becff543b3a36b38e6b3355ff5d18b0f0000c0843d1005040004000e36100204a00b08cd0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798ea02d192a39a8cc7a701730073011001020402d19683030193a38cc7b2a57300000193c2b2a57301007473027303830108cdeeac93b1a57304d18b0f0000c0af87c3210008cd0314368e16c9c99c5a6e20dda917aeb826b3a908becff543b3a36b38e6b3355ff5d18b0f00009702980304cd0302e57ca7ebf8cfa1802d4bc79a455008307a936b4f50f0629d9bef484fdd5189cd0399f5724bbc4d08c6e146d61449c05a3e0546868b1d4f83411f325187d5ca4f85cd024e06e6c6073e13a03fa4629882a69108cd60e0a9fbb2e0fcc898ce68a7051b66cd027a069cc972fc7816539a316ba1cfc0164656d63dd1873ee407670b0e8195f3bd9604cd0302e57ca7ebf8cfa1802d4bc79a455008307a936b4f50f0629d9bef484fdd5189cd0399f5724bbc4d08c6e146d61449c05a3e0546868b1d4f83411f325187d5ca4f85cd024e06e6c6073e13a03fa4629882a69108cd60e0a9fbb2e0fcc898ce68a7051b66cd027a069cc972fc7816539a316ba1cfc0164656d63dd1873ee407670b0e8195f3bdf39b03d3cb9e02d073", "hex")))
const sks = new wasm.SecretKeys()
secrets.forEach(item => sks.add(wasm.SecretKey.dlog_from_bytes(Uint8Array.from(Buffer.from(item, "hex")))))
// Array(sks.len()).fill("").forEach((item, index) => console.log(sks.get(index).get_address().to_base58(wasm.NetworkPrefix.Mainnet)))
const prover = wasm.Wallet.from_secrets(sks)
const signed = prover.sign_reduced_transaction(reduced)
console.log(JSON.stringify(signed.to_json()))
```

but running this code cause an exception in signing transaction :

```
'Transaction signing error: Prover error (tx input index 0): gf2_192 error: `Gf2_192Poly` Error: `Gf2_192Poly::interpolation`: `points.len() != values.len()`'
```

I have no idea what is the problem and how can fix it.

Our transaction have to inputs and three input (all boxes are fake boxes)

first box have this contract :

```
{
  // ----------------- REGISTERS
  // R4: Coll[Coll[Byte]] = [GUARD_PKS]
  // R5: Coll[Int] = [Payment Required Signs, Update Required Signs]
  // ----------------- TOKENS
  // 0: GuardNFT
  // --------------------
  val signedColl = SELF.R4[Coll[Coll[Byte]]].get.map { (row: Coll[Byte]) => proveDlog(decodePoint(row)) }
  val paymentSignCount = SELF.R5[Coll[Int]].get(0)
  val updateSignCount = SELF.R5[Coll[Int]].get(1)
  val updateSignLeast = atLeast(updateSignCount, signedColl)
  val paymentSignLeast = allOf(
    Coll(
      atLeast(paymentSignCount, signedColl),
      OUTPUTS(0).R4[Coll[Coll[Byte]]].get == SELF.R4[Coll[Coll[Byte]]].get,
      OUTPUTS(0).R5[Coll[Int]].get == SELF.R5[Coll[Int]].get,
    )
  )
  val guardSignBoxCheck = allOf(
    Coll(
      OUTPUTS(0).propositionBytes == SELF.propositionBytes,
      OUTPUTS(0).tokens(0)._1 == SELF.tokens(0)._1,
    )
  )
  sigmaProp(
      allOf(
        Coll(
          guardSignBoxCheck,
          paymentSignLeast || updateSignLeast
        )
      )
  )
}
```

and second have this contract

```
{
  val GuardNFT = fromBase64("GUARD_NFT");
  val guardExists = INPUTS.exists { (box: Box) => box.tokens.exists { (token: (Coll[Byte], Long)) => token._1 == GuardNFT } }
  sigmaProp(guardExists)
}
```

and boxes values as json:

```
{
  "boxId": "2f4cd0df4db787875b3a071e098b72ba4923bd2460e08184b34359563febe047",
  "value": 10000000,
  "ergoTree": "100504000400040004000402d804d601b2a5730000d602e4c6a7041ad603e4c6a70510d604ad7202d901040ecdee7204ea02d19683020193c27201c2a7938cb2db63087201730100018cb2db6308a773020001eb02ea02d19683020193e4c67201041a720293e4c672010510720398b27203730300720498b272037304007204",
  "assets": [
    {
      "tokenId": "a6ac381e6fa99929fd1477b3ba9499790a775e91d4c14c5aa86e9a118dfac853",
      "amount": 1
    }
  ],
  "additionalRegisters": {
    "R4": "1a04210302e57ca7ebf8cfa1802d4bc79a455008307a936b4f50f0629d9bef484fdd5189210399f5724bbc4d08c6e146d61449c05a3e0546868b1d4f83411f325187d5ca4f8521024e06e6c6073e13a03fa4629882a69108cd60e0a9fbb2e0fcc898ce68a7051b6621027a069cc972fc7816539a316ba1cfc0164656d63dd1873ee407670b0e8195f3bd",
    "R5": "10020608"
  },
  "creationHeight": 247249,
  "transactionId": "65c7e0d4a77ccd605b3e4812d38140f7e68fdf740cb6cdc1d8957b75138d1e4c",
  "index": 0
}
{
  "boxId": "5e8269c8e2b975a43dc6e74a9c5b10b273313c6d32c1dd40c171fc0a8852ca01",
  "value": 10000000000,
  "ergoTree": "10010e20a6ac381e6fa99929fd1477b3ba9499790a775e91d4c14c5aa86e9a118dfac853d1aea4d9010163aedb63087201d901034d0e938c7203017300",
  "assets": [],
  "additionalRegisters": {},
  "creationHeight": 247249,
  "transactionId": "2eca6f88ea99fb4fe313d94cb05c576b1b7a94ec7166aec958b36bcea4b8ff1a",
  "index": 1
}
```

### PR DESCRIPTION
**Pull request by kettlebell**
Close #597

### CODE REVIEW

File: ergotree-interpreter/src/sigma_protocol/prover.rs [hunk 1]
```diff
@@ -434,7 +434,7 @@ fn polish_simulated<P: Prover + ?Sized>(
                         for (idx, kid) in unproven_children.clone().enumerated() {
                             if kid.is_real() {
                                 count_of_real += 1;
-                                if count_of_real >= ct.k {
+                                if count_of_real > ct.k {
```
Comment (kettlebell) [inline ergotree-interpreter/src/sigma_protocol/prover.rs:437]: An off-by-one issue. Note that the associated code on scala side increments count_of_real after the conditional check(https://github.com/ScorexFoundation/sigmastate-interpreter/blob/bd1906e3a0a4f93039a357c8d3ca4343b135dcf2/sigmastate/src/main/scala/sigmastate/interpreter/ProverInterpreter.scala#L249). So this is equivalent.

File: ergotree-interpreter/src/sigma_protocol/prover.rs [hunk 2]
```diff
@@ -836,7 +836,7 @@ fn step9_real_threshold(ct: CthresholdUnproven) -> Result<Option<ProofTree>, Pro
         let mut points = Vec::new();
         let mut values = Vec::new();
         for (idx, child) in ct.children.clone().enumerated() {
-            let one_based_idx = idx + 1;
+            let one_based_idx = (idx + 1) as u8;
```
Comment (kettlebell) [inline ergotree-interpreter/src/sigma_protocol/prover.rs:839]: The fix was to make sure u8 values go into points, not an encoding of usize.

File: ergo-lib/src/wallet/signing.rs [hunk 3]
```diff
@@ -528,4 +531,24 @@ mod tests {
         );
         assert!(ver_res.unwrap().result);
     }
+
+    #[test]
```
Comment (kettlebell) [inline ergo-lib/src/wallet/signing.rs:535]: Recreated the test on rust side for easier debugging.

File: ergotree-interpreter/src/sigma_protocol/prover.rs (hunk 1 above)
Comment (kettlebell) [reply ergotree-interpreter/src/sigma_protocol/prover.rs:437]: I found this issue because the following assertion was failing: https://github.com/ergoplatform/sigma-rust/blob/b922854061bbb9a01391091128045806505b1332/ergotree-interpreter/src/sigma_protocol/sig_serializer.rs#L97-L100

Comment (greenhat) [reply ergotree-interpreter/src/sigma_protocol/prover.rs:437]: Oh wow! Great job!

**Review by greenhat — APPROVED** [review]
Looking great! Thank you!
